resources:
  - name: src_repo_1_tests_execute
    type: GitRepo
    configuration:
      gitProvider: hk_github
      path: harshkumar1/testsexecute
      branches:
        include: main

pipelines:
  - name: demo_bash_mvn_build_test
    steps:
      - name: mvn_build
        type: Bash
        configuration:
          inputResources:
            - name: src_repo_1_tests_execute
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "17"
        execution:
          onExecute:
            - pwd
            - cd $res_src_repo_1_tests_execute_resourcePath
            - pwd
            - mvn clean build
            - save_tests $res_src_repo_1_tests_execute_resourcePath/target/surefire-reports/